# KAN-154: a library's sources may include only project files that belong to
# the library or to the libraries it links (its allowlist), and no Qt GUI,
# QML, multimedia or process headers. Quoted includes are resolved like the
# compiler does (the including file's folder first, then SOURCE_DIR) and
# followed transitively, so relative and indirect includes are caught.
# Run as: cmake -DNAME=<library> -DSOURCE_DIR=<src root> -DBASE_DIR=<dir the
#   lists are relative to> -DSOURCE_LISTS=<file|file> -P CheckLibraryBoundary.cmake
# The first list holds the library's own sources; the rest are its dependencies'.
cmake_minimum_required(VERSION 3.21)
foreach(variable NAME SOURCE_DIR BASE_DIR SOURCE_LISTS)
    if(NOT DEFINED ${variable})
        message(FATAL_ERROR "CheckLibraryBoundary.cmake needs -D${variable}")
    endif()
endforeach()
set(forbidden_system "^(QtGui|QtQml|QtQuick|QtMultimedia|QtWidgets|QGuiApplication|QProcess|QQml|QQuick|QMedia|QImage|QPainter|QColor|QFont|QPixmap|rhi/)")

string(REPLACE "|" ";" SOURCE_LISTS "${SOURCE_LISTS}")
get_filename_component(source_root "${SOURCE_DIR}" REALPATH)
set(allowed "")
set(pending "")
set(first TRUE)
foreach(list_file IN LISTS SOURCE_LISTS)
    file(STRINGS "${list_file}" entries)
    foreach(entry IN LISTS entries)
        if(entry STREQUAL "")
            continue()
        endif()
        get_filename_component(path "${entry}" REALPATH BASE_DIR "${BASE_DIR}")
        string(FIND "${path}" "${source_root}/" at)
        if(NOT at EQUAL 0)
            continue() # generated sources (moc, resources) live in the build tree
        endif()
        list(APPEND allowed "${path}")
        if(first)
            list(APPEND pending "${path}")
        endif()
    endforeach()
    set(first FALSE)
endforeach()
if(NOT pending)
    message(FATAL_ERROR "${NAME}: no sources under ${source_root}")
endif()

set(visited "")
set(violations "")
while(pending)
    list(POP_FRONT pending file)
    if(file IN_LIST visited)
        continue()
    endif()
    list(APPEND visited "${file}")
    file(RELATIVE_PATH shown "${source_root}" "${file}")
    get_filename_component(folder "${file}" DIRECTORY)
    file(STRINGS "${file}" lines REGEX "^[ \t]*#[ \t]*include")
    foreach(line IN LISTS lines)
        if(line MATCHES "<([^>]+)>")
            if(CMAKE_MATCH_1 MATCHES "${forbidden_system}")
                string(APPEND violations "\n  ${shown}: ${line}")
            endif()
        elseif(line MATCHES "\"([^\"]+)\"")
            set(header "${CMAKE_MATCH_1}")
            if(header MATCHES "\\.moc$|^moc_")
                continue()
            endif()
            set(target "")
            foreach(base IN ITEMS "${folder}" "${source_root}")
                if(target STREQUAL "" AND EXISTS "${base}/${header}")
                    get_filename_component(target "${base}/${header}" REALPATH)
                endif()
            endforeach()
            if(target STREQUAL "")
                string(APPEND violations "\n  ${shown}: ${line} (not found)")
            elseif(NOT target IN_LIST allowed)
                file(RELATIVE_PATH target_shown "${source_root}" "${target}")
                string(APPEND violations "\n  ${shown}: ${line} (${target_shown} is outside ${NAME} and its dependencies)")
            else()
                list(APPEND pending "${target}")
            endif()
        endif()
    endforeach()
endwhile()
list(LENGTH visited count)
if(violations)
    message(FATAL_ERROR "${NAME} boundary violated:${violations}")
endif()
message(STATUS "${NAME} boundary holds (${count} files checked)")
